using Inverse.Domain;
using System.Text;

namespace Inverse.Plugin.ScriptGenerator.EF;

public sealed class EntityFrameworkModelGeneratorStrategy : IScriptingGeneratorStrategy
{
    public string Name => "Entity Framework Model Generator";
    public string Extension => ".cs";

    public void ExportToFile(Database database, string filename)
    {
        var exportTables = database.GetAllTablesOrderedByDependency();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {SanitizeNamespace(ToPascalCase(database.Name))}.Data;");
        sb.AppendLine();

        // Gera classes de modelo
        foreach (var table in exportTables)
        {
            sb.AppendLine(GenerateModelClass(table, database));
            sb.AppendLine();
        }

        // Gera DbContext
        sb.AppendLine(GenerateDbContext(database, exportTables));

        File.WriteAllText(filename, sb.ToString());
    }

    private static string GenerateModelClass(Table table, Database database)
    {
        var className = ToPascalCase(table.Name);
        var sb = new StringBuilder();
        sb.AppendLine($"[Table(\"{table.Name}\")]");
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        foreach (var column in table.Columns)
        {
            var propertyName = ToPascalCase(column.Name);

            // Data Annotations
            if (column.IsPrimaryKey)
                sb.AppendLine("    [Key]");

            if (column.IsForeignKey)
            {
                var fk = column as ForeignKey;
                sb.AppendLine($"    [ForeignKey(\"{ToPascalCase(fk.RelatedTable)}\")]");
            }

            if (!column.IsRequired)
                sb.AppendLine("    [Required(AllowEmptyStrings = true)]");
            else
                sb.AppendLine("    [Required]");

            if (!string.IsNullOrEmpty(column.DefaultValue))
                sb.AppendLine($"    [DefaultValue({FormatDefaultValue(column.DefaultValue, column.Type)})]");

            sb.AppendLine($"    public {MapTypeToCSharp(column.Type, !column.IsRequired)} {propertyName} {{ get; set; }}");
            sb.AppendLine();
        }

        // Navegação para Foreign Keys
        foreach (var fk in table.ForeignKeys)
        {
            var relatedClass = ToPascalCase(fk.RelatedTable);
            sb.AppendLine($"    public virtual {relatedClass} {relatedClass} {{ get; set; }}");
        }

        // Navegação inversa (coleções)
        var referencingTables = database.Tables
            .Where(t => t.ForeignKeys.Any(f => f.RelatedTable == table.Name));
        foreach (var refTable in referencingTables)
        {
            var refClass = ToPascalCase(refTable.Name);
            sb.AppendLine($"    public virtual ICollection<{refClass}> {refClass}Set {{ get; set; }} = new List<{refClass}>();");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateDbContext(Database database, IEnumerable<Table> tables)
    {
        var sb = new StringBuilder();
        sb.AppendLine("public class AppDbContext : DbContext");
        sb.AppendLine("{");
        sb.AppendLine("    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }");
        sb.AppendLine();

        foreach (var table in tables)
        {
            var className = ToPascalCase(table.Name);
            sb.AppendLine($"    public DbSet<{className}> {className} {{ get; set; }}");
        }

        sb.AppendLine();
        sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
        sb.AppendLine("    {");
        foreach (var table in tables)
        {
            var thisClass = ToPascalCase(table.Name);
            foreach (var fk in table.ForeignKeys)
            {
                var relatedClass = ToPascalCase(fk.RelatedTable);
                var fkProperty = ToPascalCase(fk.Name);
                sb.AppendLine($"        modelBuilder.Entity<{thisClass}>()");
                sb.AppendLine($"            .HasOne(e => e.{relatedClass})");
                sb.AppendLine($"            .WithMany(e => e.{thisClass}Set)");
                sb.AppendLine($"            .HasForeignKey(e => e.{fkProperty});");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string MapTypeToCSharp(string type, bool nullable)
    {
        string csType = type.ToLower() switch
        {
            "int" or "integer" => "int",
            "bigint" => "long",
            "smallint" => "short",
            "tinyint" => "byte",
            "bit" => "bool",
            "nvarchar" or "varchar" or "text" or "ntext" or "char" or "nchar" => "string",
            "datetime" or "smalldatetime" or "date" => "DateTime",
            "float" => "double",
            "real" => "float",
            "decimal" or "numeric" or "money" or "smallmoney" => "decimal",
            "uniqueidentifier" => "Guid",
            "binary" or "varbinary" or "image" => "byte[]",
            _ => "string"
        };
        if (csType != "string" && csType != "byte[]" && nullable)
            csType += "?";
        return csType;
    }

    private static string SanitizeNamespace(string name)
    {
        var valid = new string(name.Where(char.IsLetterOrDigit).ToArray());
        if (string.IsNullOrEmpty(valid))
            valid = "AppNamespace";
        if (char.IsDigit(valid[0]))
            valid = "_" + valid;
        return valid;
    }

    private static string FormatDefaultValue(string defaultValue, string type)
    {
        if (type.ToLower().Contains("char") || type.ToLower().Contains("text"))
            return $"\"{defaultValue.Replace("\"", "\\\"")}\"";
        if (type.ToLower() == "boolean" || type.ToLower() == "bit")
            return defaultValue == "1" ? "true" : "false";
        return defaultValue;
    }

    private static string ToPascalCase(string input)
    {
        if (string.IsNullOrWhiteSpace(input))
            return input;

        // Split by underscores, spaces, or dashes
        var words = input
            .Replace("-", " ")
            .Replace("_", " ")
            .Split(' ', StringSplitOptions.RemoveEmptyEntries);

        var result = new StringBuilder();
        foreach (var word in words)
        {
            if (word.Length == 0) continue;
            result.Append(char.ToUpperInvariant(word[0]));
            if (word.Length > 1)
                result.Append(word.Substring(1).ToLowerInvariant());
        }
        return result.ToString();
    }
}