<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inverse.Plugin.DatabaseGenerator.MsSqlServer\Inverse.Plugin.DatabaseGenerator.MsSqlServer.csproj" />
    <ProjectReference Include="..\Inverse.Plugin.DatabaseGenerator.Sqlite\Inverse.Plugin.DatabaseGenerator.Sqlite.csproj" />
    <ProjectReference Include="..\Inverse.Plugin.FileManager.EncryptedXml\Inverse.Plugin.FileManager.EncryptedXml.csproj" />
    <ProjectReference Include="..\Inverse.Plugin.ScriptGenerator.MsSqlServer\Inverse.Plugin.ScriptGenerator.MsSqlServer.csproj" />
  </ItemGroup>

</Project>
